CREATE TABLE ProspectProfiles (
    Id VARCHAR(36) PRIMARY KEY,
    Name VARCHAR(255),
    Role VARCHAR(255),
    Company VARCHAR(255),
    DirectReports INT,
    TeamSize INT,
    BusinessPerformanceRating INT,
    KeyChallenges TEXT,
    Objectives TEXT,
    ProgressTowardObjectives TEXT,
    MissingSkillsOrResources TEXT,
    ConfidenceLevel INT,
    HasBudget BOOLEAN,
    DecisionMakers TEXT,
    DesiredOutcome TEXT,
    Timeline VARCHAR(100),
    IsQualified BOOLEAN,
    IsFollowUpBooked BOOLEAN DEFAULT FALSE,
    PhoneNumber VARCHAR(15),
    PreferredCallTime VARCHAR(50),
    LastUpdated TIMESTAMP,
    ConversationSummary TEXT
);
